Service account resource
cockroachdb/terraform-provider-cockroach pull request #202
Opened 2024-04-20 01:12 UTC by fantapop

Added a resource for managing service accounts.

Vendor changes were put in a separate commit and are still a WIP.  That commit can be ignored. Once the necessary api changes land in production, I'll update the PR to include the correct vendor changes from the cockroach-cloud-sdk.

Also, added here is a commit to add some logging of api invocations.

**Commit checklist**
- [x] Changelog
- [x] Doc gen (`make generate`)
- [x] Integration test(s)
- [x] Acceptance test(s)
- [x] Example(s)

2024-04-24 17:30 UTC, fantapop commented on vendor/modules.txt
> +# github.com/cockroachdb/cockroach-cloud-sdk-go v1.9.0 => /Users/fitzner/go/src/github.com/cockroachdb/cockroach-cloud-sdk-go
this will not be included after I update to the actual sdk version

2024-04-24 17:30 UTC, fantapop commented on vendor/modules.txt
> +# github.com/cockroachdb/cockroach-cloud-sdk-go => /Users/fitzner/go/src/github.com/cockroachdb/cockroach-cloud-sdk-go
this will not be included after I update to the actual sdk version

2024-04-24 19:39 UTC, rgcase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/202#-:-NwGbbS3DGTiXxe-1oIW:bnfp4nl)* status: 0 of 60 files reviewed, 1 unresolved discussion (waiting on @fantapop and @pawalt)

___
*[`-- commits` line 20 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/202#-NwFyqBn7_H_Q6aR1A4N):*
super nit: typo in `udpate`


<!-- Sent from Reviewable.io -->

2024-04-24 23:06 UTC, fantapop reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/202)* status: 0 of 60 files reviewed, 3 unresolved discussions (waiting on @pawalt and @rgcase)

___
*[`-- commits` line 20 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/202#-NwFyqBn7_H_Q6aR1A4N):*
<details><summary><i>Previously, rgcase (Ryan Case) wrote…</i></summary><blockquote>

super nit: typo in `udpate`
</blockquote></details>

oh ha.  This line will get removed when I update based on the latest cloud sdk anyways.  I'll ping you to look at the updated message when that happens.


<!-- Sent from Reviewable.io -->

2024-05-01 01:00 UTC, fantapop commented
@rgcase I rebased this off main and also updated it to not overwrite the description if its not set in the resource.  Let me know what you think.

2024-05-02 17:07 UTC, rgcase requested changes
Just a couple small comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/202#-:-NwuGcu76tsg6WkK2AsZ:by7e4en)* status: 0 of 70 files reviewed, 4 unresolved discussions (waiting on @fantapop and @pawalt)

___
*[`internal/provider/service_account_resource.go` line 196 at r2](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/202#-NwuFILR11oRXnFluFru:-NwuFILR11oRXnFluFrv:b42dpai) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/5d474ff8b129b8e2646f384bc01a326b470e582e/internal/provider/service_account_resource.go#L196)):*
> ```Go
> 
> 	newName := plan.Name.ValueString()
> 	updateSpec := &client.UpdateServiceAccountSpecification{
> ```

I think you could just do
```
updateSpec := &client.UpdateServiceAccountSpecification{
  Name := plan.Name.ValueStringPointer(),
  Description := plan.Description.ValueStringPointer()
}
```
and then optionally check if they're not both null if you want, although we're already assuming here that `plan.Name` isn't null.
___
*[`internal/provider/service_account_resource_test.go` line 101 at r2](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/202#-NwuGLG18jl2fgOvcZfo:-NwuGLG18jl2fgOvcZfp:blwoouq) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/5d474ff8b129b8e2646f384bc01a326b470e582e/internal/provider/service_account_resource_test.go#L101)):*
> ```Go
> 	serviceAccountUpdated.Description = description
> 
> 	// Called by first update, description not included in resource so we don't
> ```

I don't think I understand what this comment means. Aren't we including the description in the patch?


<!-- Sent from Reviewable.io -->

2024-05-02 17:51 UTC, rgcase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/202#-:-NwuQbJsBPfM1Oa4pXBb:bnfp4nl)* status: 0 of 71 files reviewed, 3 unresolved discussions (waiting on @pawalt)



<!-- Sent from Reviewable.io -->

2024-05-02 17:52 UTC, merged